### ISSUE TITLE
Fail in before hook are considere as another test case

### ISSUE THREAD

**Issue by jeremie-val** [Shelex/cypress-allure-plugin#200]
**Bug :** 
When executing a tests, if the test succeed, it create a test case on allure side.
If the test fail in the before hook, it consider it as another test case

**To Reproduce**
1. Create a test case with a before hook.
2. Execute the same test case twice : the first time it succeed. the second time it failed in the before hook

**Expected behavior**
The test case should be the same whenever it failed (in the before / before all / after / after all hook)

**Environment (please complete the following information):**
- Cypress version:                                "^10.9.0"
- cypress-allure-plugin version:            "^2.37.0"

![Capture d’écran du 2023-03-28 12-00-57](https://user-images.githubusercontent.com/79636114/228471240-0b2b8162-bca0-4141-8320-255217e10776.png)
![Capture d’écran du 2023-03-28 12-00-52](https://user-images.githubusercontent.com/79636114/228471243-4a085261-4f12-408a-a02f-8522e23cef89.png)

**Comment by Shelex** [comment]
Thank you for opening an issue.

That ui is quite different from allure report, so I have no idea how to address it or verify.
Moreover "another test case" is identified by allure with historyId, which is a hash of the test name, so if test name was not changed - it is exactly the same execution result in allure, and will be linked to previous results if history is saved.

**Comment by jeremie-val** [comment]
Here are the 2 allure results generated from our tests : 
- The one with the hook which fail
- The one with all tests in success
[allure-results.zip](https://github.com/Shelex/cypress-allure-plugin/files/11098973/allure-results.zip)

**Comment by Shelex** [comment]
@Sheth90 your issue is not related to this one, as I do not see any failures of before hook, so I converted it to separate issue.
Further communication will be conducted in https://github.com/Shelex/cypress-allure-plugin/issues/201

**Comment by Shelex** [comment]
Hi @jeremie-val  
Issue is resolved in v2.38.3

Now plugin takes original test name for calculating history id hash.

**Comment by jeremie-val** [comment]
Thank you very much, I'll have a look.

**Comment by Sheth90** [comment]
@jeremie-val @Shelex how to install or update allure report version to v2.38.3?

**Comment by jeremie-val** [comment]
Just have to change the version in the package.json file.
That's what you did here : https://github.com/Shelex/cypress-allure-plugin/issues/201#issuecomment-1496935599

Just let @Shelex have a look :)

**Comment by Sheth90** [comment]
But still same problem persists. What to do for it? @jeremie-val As like #201

**Comment by Shelex** [comment]
@Sheth90 you have a completely separate issue so I left a comment in #201

**Comment by jeremie-val** [comment]
Validated today, a fail in a before hook is now integrated to the same test
